controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

user:
    resource: ../src/Controller/UserController.php
    type: annotation

user_edit:
    path: '/users/{id}/edit'
    controller: 'App\Controller\UserController::edit'
    requirements:
        id: '\d+'

user_delete:
    path: '/users/{id}/delete'
    controller: 'App\Controller\UserController::delete'
    requirements:
        id: '\d+'

user_block:
    path: '/users/{id}/block'
    controller: 'App\Controller\UserController::block'
    methods: ['GET'] # Adjust the HTTP method as needed
    requirements:
        id: '\d+'

user_unblock:
    path: '/user/unblock/{id}'
    controller: 'App\Controller\UserController::unblock'
    requirements:
        id: \d+  # This ensures that the "id" parameter is a digit
    methods: [GET]

blocked_user_message:
    path: '/blocked-user-message'
    controller: 'App\Controller\UserController::blockedUserMessage'